inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/Documentation:
  Exclude:
    - 'app/controllers/*'
    - 'app/mailers/*'
    - 'app/models/*'
    - 'config/application.rb'
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'