default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['DB_OWNER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DB_DEV'] %>

test:
  <<: *default
  database: <%= ENV['DB_TEST'] %>

production:
  <<: *default
  database: <%= ENV['DB_PROD'] %>
